name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do c처digo
        uses: actions/checkout@v3

      - name: Definir vers찾o da imagem
        id: version
        run: |
          echo "VERSION=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

      - name: Login no Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build e push da imagem Docker
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/hello-app:${{ env.VERSION }} .
          docker push ${{ secrets.DOCKER_USERNAME }}/hello-app:${{ env.VERSION }}

      - name: Atualizar manifest no reposit처rio ArgoCD
        run: |
          git clone https://github.com/${{ secrets.USER_GITHUB }}/hello-app-manifests.git
          cd hello-app-manifests
          sed -i "s#image: .*\$#image: ${{ secrets.DOCKER_USERNAME }}/hello-app:${{ env.VERSION }}#g" deployment.yaml
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add deployment.yaml
          git commit -m "Atualiza imagem para vers찾o ${{ env.VERSION }}"
          git push https://${{ secrets.TOKEN_GITHUB }}@github.com/${{ secrets.USER_GITHUB }}/hello-app-manifests.git


